# vim:sw=2:et:

dist: bionic

sudo: false
language: erlang
notifications:
  email:
    on_success: never
    on_failure: always
cache:
  apt: true

otp_release:
  - "23.3.1"
  - "24.0.2"


script:
  - make test xref dialyzer
